server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cstmr
    username: postgres
    password: Rm@#12345
    driver-class-name: org.postgresql.Driver
  cache:
    type: simple

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



# Feign client config for Aadhaar Service
addhar-service:
  url: http://localhost:8086/AddharService

otp-service:
  url: http://localhost:8087/OTP

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
