server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cstmr
    username: postgres
    password: Rm@#12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Feign client config for Aadhaar Service
addhar-service:
  url: http://localhost:8086/AddharService

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
